import 'react-toastify/dist/ReactToastify.css?asset';
import 'bootstrap/dist/css/bootstrap.min.css?asset';
import '@popperjs/core/dist/esm/index.js?asset';
import 'bootstrap/dist/js/bootstrap.bundle.min.js?asset';
import '@fortawesome/fontawesome-free/js/all.min.js?asset';
import 'react-confirm-alert/src/react-confirm-alert.css?asset';
import '@base/assets/icons.css?asset';
import '@base/assets/custom.css?asset';
import '@base/assets/js/app.ts?asset';